version: '3.5'
services:
    dustybot-service:
        build: 
            context: .
            dockerfile: Service/src/DustyBot.Service/Dockerfile
        image: dustybot-service
        container_name: dustybot-service
        environment:
            - TableStorageConnectionString=${Dusty_TableStorageConnectionString}
            - SqlDbConnectionString=${Dusty_SqlDbConnectionString}
            - DefaultCommandPrefix=${Dusty_DefaultCommandPrefix}
            - OwnerID=${Dusty_OwnerID}
            - BotToken=${Dusty_BotToken}
            - YouTubeKey=${Dusty_YouTubeKey}
            - LastFmKey=${Dusty_LastFmKey}
            - SpotifyId=${Dusty_SpotifyId}
            - SpotifyKey=${Dusty_SpotifyKey}
            - PapagoClientId=${Dusty_PapagoClientId}
            - PapagoClientSecret=${Dusty_PapagoClientSecret}
            - PolrKey=${Dusty_PolrKey}
            - PolrDomain=${Dusty_PolrDomain}
            - ProxyListUrl=${Dusty_ProxyListUrl}
            - ProxyListToken=${Dusty_ProxyListToken}
            - WebsiteRoot=${Dusty_WebsiteRoot}
            - WebsiteShorthand=${Dusty_WebsiteShorthand}
            - SupportServerInvite=${Dusty_SupportServerInvite}
            - SpotifyConnectUrl=${Dusty_SpotifyConnectUrl}
            - PatreonUrl=${Dusty_PatreonUrl}
            - "ElasticsearchNodeUri=http://dustybot-elasticsearch:9200"
            - "MongoDbConnectionString=mongodb://${Dusty_MongoRootUsername}:${Dusty_MongoRootPassword}@dustybot-mongodb:27017/dustybot?authSource=admin&maxPoolSize=1000"
        restart: always 
        networks:
            - dustybot-mongodb-net
            - dustybot-elasticsearch-net
        depends_on:
            - dustybot-mongodb
            - dustybot-elasticsearch

    dustybot-mongodb:
        image: mongo:4.4.3
        container_name: dustybot-mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${Dusty_MongoRootUsername}
            - MONGO_INITDB_ROOT_PASSWORD=${Dusty_MongoRootPassword}
        restart: always
        volumes:
            - dustybot-mongodb-data:/data/db
        networks: 
            - dustybot-mongodb-net

    dustybot-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        container_name: dustybot-elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - dustybot-elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - dustybot-elasticsearch-net
      
    dustybot-kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        container_name: dustybot-kibana
        ports:
            - "5601:5601"
        environment:
            - "ELASTICSEARCH_HOSTS=http://dustybot-elasticsearch:9200"
        networks:
            - dustybot-elasticsearch-net

volumes:
    dustybot-elasticsearch-data:
        name: dustybot-elasticsearch-data
        driver: local
    dustybot-mongodb-data:
        name: dustybot-mongodb-data
        driver: local

networks:
    dustybot-mongodb-net:
        name: dustybot-mongodb-net
    dustybot-elasticsearch-net:
        name: dustybot-elasticsearch-net