version: '3.4'

services:
    dustybot-service:
        extends:
            file: dustybot-service-template.yml
            service: dustybot-service
        container_name: dustybot-service
        depends_on:
            - dustybot-mongodb
            - dustybot-elasticsearch

    dustybot-mongodb:
        image: mongo:4.4.3
        container_name: dustybot-mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${Dusty_MongoRootUsername}
            - MONGO_INITDB_ROOT_PASSWORD=${Dusty_MongoRootPassword}
        restart: always
        volumes:
            - dustybot-mongodb-data:/data/db
        networks: 
            - dustybot-mongodb-net

    dustybot-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        container_name: dustybot-elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - dustybot-elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - dustybot-elasticsearch-net
      
    dustybot-kibana:
        build: 
            context: ./Kibana
            dockerfile: Dockerfile
        image: dustybot-kibana
        container_name: dustybot-kibana
        ports:
            - "5601:5601"
        environment:
            - "ELASTICSEARCH_HOSTS=http://dustybot-elasticsearch:9200"
        networks:
            - dustybot-elasticsearch-net

volumes:
    dustybot-elasticsearch-data:
        name: dustybot-elasticsearch-data
        driver: local
    dustybot-mongodb-data:
        name: dustybot-mongodb-data
        driver: local

networks:
    dustybot-mongodb-net:
        name: dustybot-mongodb-net
    dustybot-elasticsearch-net:
        name: dustybot-elasticsearch-net