version: '3.4'

services:
    dustybot-service:
        build: 
            context: .
            dockerfile: Service/src/DustyBot.Service/Dockerfile
        image: ${DOCKER_REGISTRY-}dustybot-service
        container_name: dustybot-service
        environment:
            - TableStorage__ConnectionString=${Dusty_TableStorage_ConnectionString}
            - Bot__DefaultCommandPrefix=${Dusty_DefaultCommandPrefix}
            - Bot__OwnerID=${Dusty_OwnerID}
            - Discord__Token=${Dusty_Discord_Token}
            - YouTube__ApiKey=${Dusty_YouTube_ApiKey}
            - LastFm__ApiKey=${Dusty_LastFm_ApiKey}
            - Spotify__ClientId=${Dusty_Spotify_ClientId}
            - Spotify__ClientSecret=${Dusty_Spotify_ClientSecret}
            - Papago__ClientId=${Dusty_Papago_ClientId}
            - Papago__ClientSecret=${Dusty_Papago_ClientSecret}
            - Polr__ApiKey=${Dusty_Polr_ApiKey}
            - Polr__Domain=${Dusty_Polr_Domain}
            - Web__WebsiteRoot=${Dusty_Web_WebsiteRoot}
            - Web__WebsiteShorthand=${Dusty_Web_WebsiteShorthand}
            - Web__SupportServerInvite=${Dusty_Web_SupportServerInvite}
            - Web__SpotifyConnectUrl=${Dusty_Web_SpotifyConnectUrl}
            - Web__PatreonUrl=${Dusty_Web_PatreonUrl}
            - "Logging__ElasticsearchNodeUri=http://dustybot-elasticsearch:9200"
            - "Mongo__ConnectionString=mongodb://${Dusty_Mongo_RootUsername}:${Dusty_Mongo_RootPassword}@dustybot-mongodb:27017/dustybot?authSource=admin&maxPoolSize=1000"
        restart: always 
        networks:
            - dustybot-mongodb-net
            - dustybot-elasticsearch-net

networks:
    dustybot-mongodb-net:
        name: dustybot-mongodb-net
    dustybot-elasticsearch-net:
        name: dustybot-elasticsearch-net