version: '3.4'

services:
    dustybot-service:
        build: 
            context: .
            dockerfile: Service/src/DustyBot.Service/Dockerfile
        image: ${DOCKER_REGISTRY-}dustybot-service
        container_name: dustybot-service
        environment:
            - TableStorage__ConnectionString=${Dusty_TableStorageConnectionString}
            - Bot__DefaultCommandPrefix=${Dusty_DefaultCommandPrefix}
            - Bot__OwnerID=${Dusty_OwnerID}
            - Discord__Token=${Dusty_BotToken}
            - YouTube__ApiKey=${Dusty_YouTubeKey}
            - LastFm__ApiKey=${Dusty_LastFmKey}
            - Spotify__ClientId=${Dusty_SpotifyId}
            - Spotify__ClientSecret=${Dusty_SpotifyKey}
            - Papago__ClientId=${Dusty_PapagoClientId}
            - Papago__ClientSecret=${Dusty_PapagoClientSecret}
            - Polr__ApiKey=${Dusty_PolrKey}
            - Polr__Domain=${Dusty_PolrDomain}
            - Web__WebsiteRoot=${Dusty_WebsiteRoot}
            - Web__WebsiteShorthand=${Dusty_WebsiteShorthand}
            - Web__SupportServerInvite=${Dusty_SupportServerInvite}
            - Web__SpotifyConnectUrl=${Dusty_SpotifyConnectUrl}
            - Web__PatreonUrl=${Dusty_PatreonUrl}
            - "Logging__ElasticsearchNodeUri=http://dustybot-elasticsearch:9200"
            - "Mongo__ConnectionString=mongodb://${Dusty_MongoRootUsername}:${Dusty_MongoRootPassword}@dustybot-mongodb:27017/dustybot?authSource=admin&maxPoolSize=1000"
        restart: always 
        networks:
            - dustybot-mongodb-net
            - dustybot-elasticsearch-net

networks:
    dustybot-mongodb-net:
        name: dustybot-mongodb-net
    dustybot-elasticsearch-net:
        name: dustybot-elasticsearch-net