//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustyBot.Framework.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustyBot.Framework.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command can only be used through a direct message. DM the bot to use this command..
        /// </summary>
        internal static string Command_DirectMessageOnly {
            get {
                return ResourceManager.GetString("Command_DirectMessageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. Seems that something went wrong....
        /// </summary>
        internal static string Command_GenericFailure {
            get {
                return ResourceManager.GetString("Command_GenericFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameters..
        /// </summary>
        internal static string Command_IncorrectParameters {
            get {
                return ResourceManager.GetString("Command_IncorrectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot needs the {0} permission to perform this command..
        /// </summary>
        internal static string Command_MissingBotPermissions {
            get {
                return ResourceManager.GetString("Command_MissingBotPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot needs the {0} permissions to perform this command..
        /// </summary>
        internal static string Command_MissingBotPermissionsMultiple {
            get {
                return ResourceManager.GetString("Command_MissingBotPermissionsMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required permissions for this command ({0})..
        /// </summary>
        internal static string Command_MissingPermissions {
            get {
                return ResourceManager.GetString("Command_MissingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is for the bot owner only..
        /// </summary>
        internal static string Command_NotOwner {
            get {
                return ResourceManager.GetString("Command_NotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Command_Usage {
            get {
                return ResourceManager.GetString("Command_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a parameter contains spaces, add quotes: &quot;he llo&quot;. Parameters marked &quot;...&quot; need no quotes..
        /// </summary>
        internal static string Command_UsageFooter {
            get {
                return ResourceManager.GetString("Command_UsageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string Common_WordListLastSeparator {
            get {
                return ResourceManager.GetString("Common_WordListLastSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string Common_WordListSeparator {
            get {
                return ResourceManager.GetString("Common_WordListSeparator", resourceCulture);
            }
        }
    }
}
